# Generated by Django 3.0.7 on 2021-05-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employee_data',
        ),
    ]
